version: '2'

services:
  ## Smarthome containers ##
  # MQTT Broker for MQTT devices and the rfplugs service
  mqtt:
    restart: on-failure
    image: "eclipse-mosquitto:latest"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes: 
      - "./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"  
      - "./config/mosquitto/mosquitto_passwords:/mosqitto/config/mosquitto_passwords"  
      - "./log/mosquitto:/mosquitto/log/"

  # home assistant instance
  home-assistant:
    restart: on-failure
    image: "homeassistant/home-assistant:latest"
    # needed for homekit?!
    network_mode: "host"
    ports:
      - "8123:8123"
      - "51827:51827"
    volumes:
      # configs
      - "./config/ha/automations.yaml:/config/automations.yaml"
      - "./config/ha/configuration.yaml:/config/configuration.yaml"
      - "./config/ha/groups.yaml:/config/groups.yaml"
      - "./config/ha/scripts.yaml:/config/scripts.yaml"
      - "./config/ha/ui-lovelace.yaml:/config/ui-lovelace.yaml"
      - "./config/ha/ha_secrets.yaml:/config/secrets.yaml"
      # data files
      - "./data/ha:/config/"
      # - "./ha/data/.storage:/config/.storage"
      # - "./ha/data/.homekit.state:/config/.homekit.state"
      # misc
      - "./log/home-assistant.log:/config/home-assistant.log"
      - "/etc/localtime:/etc/localtime:ro"
      #- "./data/wifi.svg:/config/www/wifi.svg"
  # deconz for all zigbee devices
  deconz:
    image: marthoc/deconz:latest
    #container_name: deconz
    network_mode: host
    restart: on-failure
    ports:
      - "9080:9080"
      - "9443:9443"
    devices:
      - /dev/ttyUSB0
    volumes:
      - ./data/deconz:/root/.local/share/dresden-elektronik/deCONZ
    environment:
      - DECONZ_WEB_PORT=9080
      - DECONZ_WS_PORT=9443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0

  # node red for automation
  node-red:
    restart: on-failure
    image: nodered/node-red
    environment:
      - TZ=Europe/Berlin
    volumes:
      - "./data/node-red:/data"
      - "./config/node-red/settings.js:/data/settings.js"
    ports:
      - "1880:1880"

  ## Network, control and utilities
  # unifi for wifi management
  unifi:
    restart: on-failure
    image: jacobalberty/unifi:latest
    network_mode: host
    environment:
      - TZ=Europe/Berlin
      - RUNAS_UID0=false
      - UNIFI_UID=950
      - UNIFI_GID=950
    volumes:
    - ./log/unifi:/unifi/log
    - ./data/unifi:/unifi/data

  # portainer for docker management
  portainer:
    image: portainer/portainer:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data/portainer:/data"
    ports:
      - "9000:9000"
    restart: on-failure

  # cloudflare ddns
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: on-failure
    env_file:
      - "config/cloudflare_creds.env"